services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: popcorn-ddb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    volumes:
      - ./.dynamodb-local:/home/dynamodblocal/data
